name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: List Files After Checkout
        run: |
          pwd
          ls
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Joshua
      - name: Log Greeting Time From Previous Step
        run: echo "${{ steps.greet.outputs.time }}"
